## a pair of functions that cache the inverse of a matrix.

## the makeCacheMatrix function returns a list of functions.

makeCacheMatrix <- function(x = matrix()) {
        m_1 <- NULL
        set <- function(y) {
                x <<- y
                m_1 <<- NULL
        }
        get <- function() x
        set_inv <- function(inv) m_1 <<- inv
        get_inv <- function() m_1
        list(set = set, get = get, set_inv = set_inv, get_inv = get_inv)
}


## argument "x" is a list generated by the makeCacheMatrix function.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m_1 <- x$get_inv()
        if (!is.null(m_1)) {
                message("Getting cached matrix:")
                return(m_1)
        }
        m <- x$get()
        m_1 <- solve(m)
        x$set_inv(m_1)
        m_1        
}

## sample runs:
# > mtx3 <- matrix(c(2, 3, 4, 6, 7, 10, 2, 55, 11), nrow =3, ncol=3)
# > mtx3_c <- makeCacheMatrix(mtx3)
# > cacheSolve(mtx3_c)
# [,1]        [,2]        [,3]
# [1,] -2.62777778 -0.25555556  1.75555556
# [2,]  1.03888889  0.07777778 -0.57777778
# [3,]  0.01111111  0.02222222 -0.02222222
# > cacheSolve(mtx3_c)
# Getting cached matrix:
#         [,1]        [,2]        [,3]
# [1,] -2.62777778 -0.25555556  1.75555556
# [2,]  1.03888889  0.07777778 -0.57777778
# [3,]  0.01111111  0.02222222 -0.02222222